// =============================================================
// gear.js — Your personal camera kit data for junqing.github.io
// =============================================================
// HOW TO EDIT FROM ANOTHER DEVICE:
//   1. Go to https://github.com/junqing/junqing.github.io
//   2. Click gear.js → pencil icon (Edit this file)
//   3. Make your changes, then click "Commit changes"
//   4. GitHub Pages rebuilds in ~1 minute — refresh the site to see updates.
//
// RECIPE NAMES: custom-slot and FS recipe_name values must exactly match
// a name in recipes-v.js. Browse Camera Settings → X-Trans V → Recipes
// and copy the name precisely. MY_RECIPES is an empty future-use reserve.
// =============================================================


// ─── YOUR CAMERAS ────────────────────────────────────────────
const MY_CAMERAS = [
  {
    name: "Fujifilm X-M5",
    subtitle: "Compact / content creator",
    icon: "📷",
    image: "images/gear/x-m5.jpg",
    specs: [
      ["Model",      "X-M5"],
      ["Sensor",     "26.1MP X-Trans CMOS 4"],
      ["Processor",  "X-Processor 5"],
      ["Mount",      "Fujifilm X"],
      ["IBIS",       "None"],
      ["EVF",        "None"],
      ["Released",   "November 2024"],
    ],
    notes: "Compact, lightweight vlog-friendly body. Great for everyday carry and travel — pairs beautifully with the pancake primes."
  },
  {
    name: "Fujifilm X-T50",
    subtitle: "High-resolution primary body",
    icon: "📷",
    image: "images/gear/x-t50.jpg",
    specs: [
      ["Model",      "X-T50"],
      ["Sensor",     "40.2MP X-Trans CMOS 5 HR"],
      ["Processor",  "X-Processor 5"],
      ["Mount",      "Fujifilm X"],
      ["IBIS",       "Up to 7.0 stops"],
      ["Film Sim Dial", "Yes"],
      ["Released",   "June 2024"],
    ],
    notes: "The main workhorse. 40MP gives headroom to crop, and the dedicated film-simulation dial makes swapping between recipes tactile and fast."
  },
  {
    name: "Olympus PEN-F",
    subtitle: "Retro-styled M43 body",
    icon: "📷",
    image: "images/gear/pen-f.jpg",
    image_credit: "Photo: 之乎 (Search255) / CC BY-SA 4.0, Wikimedia Commons",
    specs: [
      ["Model",      "PEN-F"],
      ["Sensor",     "20.3MP Live MOS"],
      ["Processor",  "TruePic VII"],
      ["Mount",      "Micro Four Thirds"],
      ["IBIS",       "5-axis"],
      ["EVF",        "Built-in, 2.36M-dot"],
      ["Released",   "January 2016"],
    ],
    notes: "Retro rangefinder-styled body with a dedicated front Color/Mono Creative dial — brings the same tactile recipe-dialing feel to the M43 side of the kit."
  },
  {
    name: "OM System OM-3",
    subtitle: "Weather-sealed creative / computational M43 body",
    icon: "📷",
    image: "images/gear/om-3.jpg",
    image_credit: "Product photo: OM SYSTEM",
    specs: [
      ["Model",      "OM-3"],
      ["Sensor",     "20.4MP stacked BSI Live MOS"],
      ["Processor",  "TruePic X"],
      ["Mount",      "Micro Four Thirds"],
      ["IBIS",       "5-axis"],
      ["EVF",        "Built-in, 2.36M-dot"],
      ["Weather sealing", "IP53 (with a suitably sealed lens)"],
      ["Creative dial", "Color / Mono profiles, Art filters, Color Creator"],
      ["Custom modes", "C1–C5"],
      ["Released",   "February 2025"],
    ],
    notes: "Pairs with the existing M43 lenses. The Creative dial keeps color and monochrome looks tactile, while the CP button brings computational tools such as High Res Shot, Live ND, and Live GND within reach. Weather resistance depends on the lens too."
  },
];


// ─── YOUR LENSES ─────────────────────────────────────────────
const MY_LENSES = [
  {
    name: "XF 23mm f/2.8 R WR",
    subtitle: "Pancake wide prime · 35mm equiv.",
    icon: "🔭",
    image: "images/gear/xf23f28.jpg",
    mount: "X",
    specs: [
      ["Focal length",   "23mm (35mm equiv.)"],
      ["Max aperture",   "f/2.8"],
      ["Type",           "Prime — pancake"],
      ["Weather sealed", "Yes"],
      ["Filter thread",  "39mm"],
      ["Weight",         "90g"],
    ],
    notes: "Featherweight pancake that barely adds any size to either body. Great walk-around lens when you want to travel light."
  },
  {
    name: "XF 27mm f/2.8 R WR",
    subtitle: "Pancake standard prime · 41mm equiv.",
    icon: "🔭",
    image: "images/gear/xf27f28.jpg",
    mount: "X",
    specs: [
      ["Focal length",   "27mm (41mm equiv.)"],
      ["Max aperture",   "f/2.8"],
      ["Type",           "Prime — pancake"],
      ["Weather sealed", "Yes"],
      ["Filter thread",  "39mm"],
      ["Weight",         "84g"],
    ],
    notes: "The flattest lens in the kit — virtually disappears on the X-M5. A natural field-of-view close to how the eye sees."
  },
  {
    name: "XF 23mm f/2 R WR",
    subtitle: "Compact wide prime · 35mm equiv.",
    icon: "🔭",
    image: "images/gear/xf23f2.webp",
    mount: "X",
    specs: [
      ["Focal length",   "23mm (35mm equiv.)"],
      ["Max aperture",   "f/2"],
      ["Type",           "Prime"],
      ["Weather sealed", "Yes"],
      ["Filter thread",  "43mm"],
      ["Weight",         "180g"],
    ],
    notes: "One stop faster than the f/2.8 pancake with only a modest size increase. Good balance for low-light street work."
  },
  {
    name: "XF 35mm f/2 R WR",
    subtitle: "Compact standard prime · 53mm equiv.",
    icon: "🔭",
    image: "images/gear/xf35f2.webp",
    mount: "X",
    specs: [
      ["Focal length",   "35mm (53mm equiv.)"],
      ["Max aperture",   "f/2"],
      ["Type",           "Prime"],
      ["Weather sealed", "Yes"],
      ["Filter thread",  "43mm"],
      ["Weight",         "170g"],
    ],
    notes: "Versatile and sharp from wide open. Reaches a classic portrait field-of-view and handles casual street and food shots equally well."
  },
  {
    name: "XF 35mm f/1.4 R",
    subtitle: "Classic fast prime · 53mm equiv.",
    icon: "🔭",
    image: "images/gear/xf35f14.webp",
    mount: "X",
    specs: [
      ["Focal length",   "35mm (53mm equiv.)"],
      ["Max aperture",   "f/1.4"],
      ["Type",           "Prime"],
      ["Weather sealed", "No"],
      ["Filter thread",  "52mm"],
      ["Weight",         "187g"],
    ],
    notes: "The OG Fuji lens with that distinctive creamy rendering. Slower to focus but the character at f/1.4–f/2 is unmatched in the kit."
  },
  {
    name: "XF 16-50mm f/2.8-4.8 R LM WR",
    subtitle: "Standard zoom · 24-76mm equiv.",
    icon: "🔭",
    image: "images/gear/xf16-50.jpg",
    mount: "X",
    specs: [
      ["Focal length",   "16-50mm (24-76mm equiv.)"],
      ["Max aperture",   "f/2.8-4.8"],
      ["Type",           "Zoom"],
      ["Weather sealed", "Yes"],
      ["Filter thread",  "58mm"],
      ["Weight",         "240g"],
    ],
    notes: "The kit lens bundled with the X-T50. Surprisingly capable — covers wide through short tele and is compact enough not to feel burdensome."
  },
  {
    name: "XF 18-55mm f/2.8-4 R LM OIS",
    subtitle: "Standard zoom with OIS · 27-84mm equiv.",
    icon: "🔭",
    image: "images/gear/xf18-55.webp",
    mount: "X",
    specs: [
      ["Focal length",   "18-55mm (27-84mm equiv.)"],
      ["Max aperture",   "f/2.8-4"],
      ["Type",           "Zoom"],
      ["Weather sealed", "No"],
      ["OIS",            "Yes (4-stop)"],
      ["Filter thread",  "58mm"],
      ["Weight",         "310g"],
    ],
    notes: "The tried-and-true X-mount kit zoom. Slightly longer reach than the 16-50, and the OIS helps on the X-M5 which lacks IBIS."
  },
  {
    name: "M.Zuiko Digital ED 14-42mm f/3.5-5.6 EZ",
    subtitle: "Pancake kit zoom · 28-84mm equiv.",
    icon: "🔭",
    image: "images/gear/zuiko14-42.jpg",
    mount: "M43",
    specs: [
      ["Focal length",   "14-42mm (28-84mm equiv.)"],
      ["Max aperture",   "f/3.5-5.6"],
      ["Type",           "Zoom — power pancake"],
      ["Weather sealed", "No"],
      ["Filter thread",  "37mm"],
      ["Weight",         "93g"],
    ],
    notes: "Motorized power-zoom pancake — collapses flat against the PEN-F for a genuinely pocketable everyday kit."
  },
  {
    name: "Lumix G 20mm f/1.7 ASPH",
    subtitle: "Fast standard pancake · 40mm equiv.",
    icon: "🔭",
    image: "images/gear/lumix20f17.jpg",
    image_credit: "Photo: Ermell / CC BY-SA 4.0, Wikimedia Commons",
    mount: "M43",
    specs: [
      ["Focal length",   "20mm (40mm equiv.)"],
      ["Max aperture",   "f/1.7"],
      ["Type",           "Prime — pancake"],
      ["Weather sealed", "No"],
      ["Filter thread",  "46mm"],
      ["Weight",         "100g"],
    ],
    notes: "The original (not the II) — a bit slower to autofocus than newer designs, but the rendering is still a favorite for low-light and everyday shooting."
  },
  {
    name: "M.Zuiko Digital 17mm f/2.8",
    subtitle: "Wide pancake prime · 34mm equiv.",
    icon: "🔭",
    image: "images/gear/zuiko17f28.jpg",
    image_credit: "Photo: Melv_L / CC BY-SA 2.0, Wikimedia Commons",
    mount: "M43",
    specs: [
      ["Focal length",   "17mm (34mm equiv.)"],
      ["Max aperture",   "f/2.8"],
      ["Type",           "Prime — pancake"],
      ["Weather sealed", "No"],
      ["Filter thread",  "37mm"],
      ["Weight",         "71g"],
    ],
    notes: "Ultra-thin pancake prime, similar footprint to the XF 27mm on the Fuji side. Simple, fast to focus, easy to always have on the body."
  },
  {
    name: "M.Zuiko Digital 17mm f/1.8",
    subtitle: "Fast wide prime · 34mm equiv.",
    icon: "🔭",
    image: "images/gear/zuiko17f18-ii.jpg",
    image_credit: "Photo: Sam Trenholme / CC BY 4.0, Wikimedia Commons",
    mount: "M43",
    specs: [
      ["Focal length",   "17mm (34mm equiv.)"],
      ["Max aperture",   "f/1.8"],
      ["Type",           "Prime"],
      ["Weather sealed", "No"],
      ["Filter thread",  "46mm"],
      ["Weight",         "120g"],
    ],
    notes: "A full stop faster than the f/2.8 pancake with a metal focus-clutch barrel for manual-focus feel. The go-to fast wide prime on the M43 side."
  },
];


// ─── CUSTOM SLOTS C1–C7 ──────────────────────────────────────
// type "multi"  → one set of base settings shared across all film simulations.
//                 Rotate the film dial or change Film Sim in the menu to explore each look.
// type "single" → one recipe per slot; settings listed below.
const MY_CUSTOM_SLOTS = [
  {
    slot: "C1",
    camera: "Fujifilm X-T50",
    name: "X-T50 Film Dial — Universal Recipe",
    source_url: "https://fujixweekly.com/2024/05/16/fujifilm-x-t50-film-dial-settings-14-new-film-simulation-recipes-yes-14/",
    type: "multi",
    description: "One base configuration used across all 14 film simulations via the X-T50's physical Film Dial. Base settings are warm-leaning (Auto WB White Priority, Color +3) — designed so each simulation looks good without per-sim tweaking. Spinning the dial mid-shoot is instant and tactile, making it easy to experiment on the fly.",
    usage: "Best in natural and golden-hour light — the warm base (Auto WB White Priority, R+2/B−4, Color +3) pushes most sims into warm-balanced territory. Good for travel, outdoor events, people, and casual street where you want rich, flattering colour without thinking. Avoid in artificial or mixed indoor light where Auto WB can drift warm unpredictably.",
    pros: [
      "Physical dial makes switching simulations instant — no menu diving",
      "Warm color tuning (R+2/B−4) works well in natural light and golden hour",
      "Covers both color and B&W in a single saved slot",
      "Relatively forgiving — Auto WB adapts to mixed indoor/outdoor light",
    ],
    cons: [
      "X-T50 only — not usable on X-M5 (no film dial)",
      "Color +3 can clip saturation in vivid sims like Velvia — meter carefully",
      "Some sims (Sepia, Reduced Bleach) are rarely useful day-to-day",
      "Auto WB can shift noticeably between shots in changing light",
    ],
    base_settings: [
      ["Dynamic Range", "DR400"],
      ["Grain", "Weak, Small"],
      ["CCE", "Strong"],
      ["CCE Blue", "Weak"],
      ["White Balance", "Auto White Priority  R+2 / B−4"],
      ["Highlight", "−1.5"],
      ["Shadow", "−1"],
      ["Color", "+3"],
      ["Sharpness", "−1"],
      ["Clarity", "−2"],
      ["ISO Max", "6400"],
      ["Exposure", "0 to +1"],
    ],
    simulations: [
      { film_sim: "Provia/STD",          label: "Standard Film",           recipe_name: "Standard Film (X-T50 Film Dial)", character: "Bright, warm, slightly Fujichrome Provia 100F with a warming filter feel." },
      { film_sim: "Velvia/Vivid",         label: "Velvia Film",             recipe_name: "Velvia Film (X-T50 Film Dial)", character: "Vibrant reversal film rendering. Avoid for portraits." },
      { film_sim: "Astia/Soft",           label: "Astia Summer",            recipe_name: "Astia Summer (X-T50 Film Dial)", character: "High saturation with flat tonality — between Provia and Velvia." },
      { film_sim: "Classic Chrome",       label: "Kodak Film",              recipe_name: "Kodak Film (X-T50 Film Dial)", character: "Contrasty, muted Kodak palette. Versatile including portraits." },
      { film_sim: "Reala Ace",            label: "Fujicolor PRO 160C Warm", recipe_name: "Fujicolor PRO 160C Warm (X-T50 Film Dial)", character: "Warm professional color negative. Works in multiple situations." },
      { film_sim: "Classic Negative",     label: "Superia Negative",        recipe_name: "Superia Negative (X-T50 Film Dial)", character: "Lower saturation, higher contrast. Excels in low-contrast lighting." },
      { film_sim: "Nostalgic Neg.",       label: "Nostalgic Film",          recipe_name: "Nostalgic Film (X-T50 Film Dial)", character: "Warmest option. 1970s Kodak retro rendering." },
      { film_sim: "PRO Neg. Hi",          label: "PRO Negative Hi",         recipe_name: "Fujicolor PRO Film (X-T50 Film Dial)", character: "Balanced professional rendering, slightly more saturated than Reala Ace." },
      { film_sim: "PRO Neg. Std",         label: "PRO Negative Std",        recipe_name: "Fujicolor PRO 160S (X-T50 Film Dial)", character: "Lower saturation than Hi. Particularly strong for portraiture." },
      { film_sim: "Eterna/Cinema",        label: "Cinematic Film",          recipe_name: "Cinematic Film (X-T50 Film Dial)", character: "Lowest saturation, softest quality. Tames overly bright conditions." },
      { film_sim: "Eterna Bleach Bypass", label: "Reduced Bleach",          recipe_name: "Reduced Bleach (X-T50 Film Dial)", character: "Highest contrast, minimal color. Unique cinematic appearance." },
      { film_sim: "Acros",               label: "Neopan Negative",         recipe_name: "Neopan Negative (X-T50 Film Dial)", character: "Low-contrast monochrome. Best in high-contrast scenes." },
      { film_sim: "Monochrome",           label: "Monochrome",              recipe_name: "Monochrome Film (X-T50 Film Dial)", character: "Standard grayscale. Best with high-contrast subjects." },
      { film_sim: "Sepia",               label: "Sepia Print",             recipe_name: "Sepia Print (X-T50 Film Dial)", character: "Warm brown tone. Rarely used but available." },
    ],
  },
  {
    slot: "C2",
    camera: "both",
    name: "Universal Negative 14",
    source_url: "https://fujixweekly.com/2025/03/28/universal-negative-14-fujifilm-x100vi-x-trans-v-film-simulation-recipes-yes-14/",
    type: "multi",
    description: "14 distinct looks sharing one set of base settings — dial-style exploration without saving 14 separate recipes. Settings are tuned for a negative-film character: pulled contrast, restrained color, DR400 highlight protection and softer Shadow −2 rendering. Rotate through simulations to find the right mood; the base settings hold across all of them.",
    usage: "Versatile across lighting conditions — the muted, neutral-to-cool base (Color −2, 4000K) keeps most sims flat and analogue-pulled rather than vivid. Reach for it in overcast, indoor natural light, golden hour, or mixed light where a neutral character works in your favour. Not the first choice for punchy sunny scenes or portraits where warm skin tones matter.",
    pros: [
      "Single recipe to remember — only the Film Sim changes",
      "Covers the entire tonal spectrum from punchy color to gritty B&W",
      "DR400 + Shadow −2 gives excellent dynamic range for backlit or tricky light",
      "Great for learning what each simulation actually does side-by-side",
    ],
    cons: [
      "14 options is a lot to keep in mind — takes time to internalize which to reach for",
      "Eterna and Sepia sims have narrow situational use and are easy to forget",
      "Color −2 means saturated subjects may look a bit muted — may want +⅔ EV more",
      "Not optimized for portraits (cooler WB and reduced color can flatten skin tones)",
    ],
    base_settings: [
      ["Dynamic Range", "DR400"],
      ["Grain", "Strong, Small"],
      ["CCE", "Strong"],
      ["CCE Blue", "Strong"],
      ["White Balance", "4000K  R0 / B−5"],
      ["Highlight", "0"],
      ["Shadow", "−2"],
      ["Color", "−2"],
      ["Sharpness", "−2"],
      ["ISO Max", "6400"],
      ["Exposure", "−⅓ to +⅔"],
    ],
    simulations: [
      { film_sim: "Provia/STD",          label: "Universal Provia",        recipe_name: "Universal Provia", character: "Balanced, true-to-life with a slight analog vibe. Versatile in daylight." },
      { film_sim: "Velvia/Vivid",         label: "Velvia 100F",             recipe_name: "Velvia 100F", character: "Vibrant without being garish. Best for colorful scenes in sunny or golden light." },
      { film_sim: "Astia/Soft",           label: "Indoor Astia",            recipe_name: "Indoor Astia", character: "Soft tones, favorite for indoor natural light. Works across varied lighting." },
      { film_sim: "Classic Chrome",       label: "Elite Chrome",            recipe_name: "Elite Chrome", character: "Kodak slide film feel. Best in direct sunny daylight." },
      { film_sim: "Reala Ace",            label: "Retro Negative",          recipe_name: "Retro Negative", character: "Evokes 1980s–90s color negative. Excellent at golden hour and blue hour." },
      { film_sim: "PRO Neg. Hi",          label: "Fuji Negative",           recipe_name: "Fuji Negative", character: "General Fujicolor negative character. Performs well in overcast conditions." },
      { film_sim: "PRO Neg. Std",         label: "Pulled Negative",         recipe_name: "Pulled Negative", character: "Low-contrast, mimics film pull processing. Ideal for artificial light." },
      { film_sim: "Classic Negative",     label: "Fujicolor Superia 200",   recipe_name: "Fujicolor Superia 200", character: "Author's favorite. Indoor natural and artificial light. Versatile workhorse." },
      { film_sim: "Nostalgic Neg.",       label: "Americana Film",          recipe_name: "Americana Film", character: "Warmest option. Modeled after American New Color photography from the 1970s." },
      { film_sim: "Eterna/Cinema",        label: "Eterna Film",             recipe_name: "Eterna Film", character: "Soft, cinematic. Tames high-contrast scenes. Limited but effective use cases." },
      { film_sim: "Eterna Bleach Bypass", label: "Chrome City",             recipe_name: "Chrome City", character: "High contrast, low saturation. Reminiscent of LomoChrome Metropolis film." },
      { film_sim: "Acros",               label: "Acros Negative",          recipe_name: "Acros Negative", character: "Low-contrast B&W. Thrives in high-contrast scenes." },
      { film_sim: "Monochrome",           label: "B&W Negative",            recipe_name: "B&W Negative", character: "Harsher tonality than Acros. Benefits from filter adjustments." },
      { film_sim: "Sepia",               label: "B&W Sepia",               recipe_name: "B&W Sepia", character: "Reddish-brown toning for stylistic or archival aesthetics." },
    ],
  },
  {
    slot: "C3",
    camera: "both",
    name: "Reggie's Portra",
    source_url: "https://fujixweekly.com/2022/06/11/fujifilm-x-trans-iv-film-simulation-recipe-reggies-portra/",
    type: "single",
    recipe_name: "Reggie's Portra",
    description: "Emulates Kodak Portra 400 processed at Richard Photo Lab — not a clinical Portra clone, but a warm and slightly saturated take on what premium C-41 looks like with a skilled developing lab. Classic Chrome + CCE Strong lifts midtones and adds depth without going full slide-film punchy. Auto WB keeps it usable anywhere.",
    usage: "Everyday carry. Portraits, street, travel, casual events. Auto WB keeps it consistent across mixed lighting.",
    pros: [
      "Auto WB means you can leave it on all day without thinking",
      "Flattering for portraits — warm tones and −1 shadow lift skin tones nicely",
      "Soft sharpness (−2) hides harsh edges and makes files feel more filmic",
      "Classic Chrome gives a slight muted quality without losing saturation",
    ],
    cons: [
      "Not a faithful Portra clone — more like a 'Portra-inspired' interpretation",
      "Color +2 can push already-saturated subjects (sunsets, flowers) a bit far",
      "Auto WB can vary between scenes; check consistency across a series of portraits",
      "DR Auto may underexpose highlights in tricky high-contrast scenes; consider DR200",
    ],
    settings: [
      ["Film Sim",       "Classic Chrome"],
      ["Dynamic Range",  "DR Auto"],
      ["Grain",          "Weak, Small"],
      ["CCE",            "Strong"],
      ["CCE Blue",       "Weak"],
      ["White Balance",  "Auto  R+2 / B−4"],
      ["Highlight",      "−1"],
      ["Shadow",         "−1"],
      ["Color",          "+2"],
      ["Sharpness",      "−2"],
      ["ISO Max",        "6400"],
    ],
  },
  {
    slot: "C4",
    camera: "both",
    name: "Kodachrome 64",
    recipe_name: "Kodachrome 64",
    source_url: "https://fujixweekly.com/2022/11/28/kodachrome-64-fujifilm-x-t5-x-trans-v-film-simulation-recipe/",
    type: "single",
    description: "Mimics the third era of Kodachrome (1974–2009) — that specific ISO 64 emulsion with its warm skin tones, cyan-shifted skies, and moderately punchy contrast. Clarity +3 and Sharpness +1 give it the crisp, defined quality that made Kodachrome a standard for photojournalism and National Geographic. Strictly a daylight recipe.",
    usage: "Sunny outdoor only. Landscapes, gardens, desert, city architecture, travel. Use Daylight WB — avoid indoors.",
    pros: [
      "Iconic cyan-blue sky rendering — looks instantly like classic Kodachrome slides",
      "Clarity +3 + Sharpness +1 gives excellent micro-contrast and edge definition",
      "DR200 handles midday contrast well without blown highlights",
      "Daylight WB means consistent color across all sunny shots",
    ],
    cons: [
      "Strictly sunny daylight only — falls apart quickly in overcast, shade, or indoors",
      "Warm skin tones from the WB shift can look ruddy on some complexions",
      "Sharpness +1 makes noise more visible at higher ISO — keep it at base ISO",
      "Low-ISO nature means less latitude in exposure; nail it in-camera",
    ],
    settings: [
      ["Film Sim",       "Classic Chrome"],
      ["Dynamic Range",  "DR200"],
      ["Grain",          "Weak, Small"],
      ["CCE",            "Strong"],
      ["CCE Blue",       "Off"],
      ["White Balance",  "Daylight  R+2 / B−5"],
      ["Highlight",      "0"],
      ["Shadow",         "+0.5"],
      ["Color",          "+2"],
      ["Sharpness",      "+1"],
      ["Clarity",        "+3"],
      ["ISO Max",        "6400"],
      ["Exposure",       "0 to +⅔"],
    ],
  },
  {
    slot: "C5",
    camera: "both",
    name: "Kodak Gold 200",
    recipe_name: "Kodak Gold 200",
    source_url: "https://fujixweekly.com/2023/10/24/kodak-gold-200-fujifilm-x-t5-x-trans-v-film-simulation-recipe/",
    type: "single",
    description: "Emulates Kodak Gold 200 (introduced 1986) — that consumer-tier color negative with its characteristic warm, slightly yellow-shifted look and dense shadows. R+4/B−5 is an extreme WB push that makes sunlit scenes glow; the strong grain and defined shadows give it the slightly rough, memory-photo quality that defines Gold 200's character.",
    usage: "Sunny daylight — beach, travel, nature, outdoor events. Lean into the warmth; expose a stop above camera meter.",
    pros: [
      "Authentic Kodak Gold warmth — sunlit scenes have a rich, nostalgic glow",
      "Strong, Small grain adds texture that feels genuinely filmic",
      "Shadow +0.5 gently deepens dark tones; DR400 protects highlights rather than lifting shadows",
      "Works beautifully on film-centric subjects: people at the beach, summer events",
    ],
    cons: [
      "Extreme WB shift (R+4/B−5) makes indoor or artificial-light shots very yellow",
      "Color +3 + Highlight −1.5 means oversaturated subjects (red flowers, neon signs) may clip",
      "Not for portraits where accurate skin tone matters",
      "Requires EV +⅔ to +1 — easy to underexpose if you forget to dial it in",
    ],
    settings: [
      ["Film Sim",       "Classic Chrome"],
      ["Dynamic Range",  "DR400"],
      ["Grain",          "Strong, Small"],
      ["CCE",            "Weak"],
      ["CCE Blue",       "Off"],
      ["White Balance",  "Daylight  R+4 / B−5"],
      ["Highlight",      "−1.5"],
      ["Shadow",         "+0.5"],
      ["Color",          "+3"],
      ["Sharpness",      "−2"],
      ["Clarity",        "−2"],
      ["ISO Max",        "6400"],
      ["Exposure",       "+⅔ to +1"],
    ],
  },
  {
    slot: "C6",
    camera: "both",
    name: "Pacific Blues",
    recipe_name: "Pacific Blues",
    source_url: "https://fujixweekly.com/2022/12/06/pacific-blues-fujifilm-x-t5-x-trans-v-film-simulation-recipe/",
    type: "single",
    description: "Inspired by Lucy Laucht's Spirit of Summer series — warm and ethereal, with stronger shadow contrast (Shadow +3) and soft clarity that make the image feel like memory rather than documentation. Classic Negative + CCE Strong gives depth without harshness. Despite the dreamy look it's unusually versatile: Laucht's original samples span fog, desert, interiors, and portraits.",
    usage: "Golden hour, beach, garden, dreamy portraits, overcast or foggy days. Try it in more situations than you'd expect — it adapts.",
    pros: [
      "Shadow +3 adds depth while Clarity −3 softens micro-contrast — a deliberately textured combination",
      "Surprisingly versatile — handles soft light, overcast, and even night portraits well",
      "Large grain adds tactile film texture without looking gritty",
      "Classic Negative has the most filmic tonal roll-off of all Fuji sims",
    ],
    cons: [
      "Shadow +3 deepens dark tones; check important shadow detail in high-contrast light",
      "Large grain can look excessive at high ISO; best at ISO 400 or below",
      "Color +4 may oversaturate vivid subjects (tropical flowers, neon lights)",
      "5800K WB shift can cast warm on skin in mixed/cool indoor lighting",
    ],
    settings: [
      ["Film Sim",       "Classic Negative"],
      ["Dynamic Range",  "DR400"],
      ["Grain",          "Strong, Large"],
      ["CCE",            "Strong"],
      ["CCE Blue",       "Weak"],
      ["White Balance",  "5800K  R+1 / B−3"],
      ["Highlight",      "−2"],
      ["Shadow",         "+3"],
      ["Color",          "+4"],
      ["Sharpness",      "−2"],
      ["Clarity",        "−3"],
      ["ISO Max",        "6400"],
      ["Exposure",       "+⅔ to +1"],
    ],
  },
  {
    slot: "C7",
    camera: "both",
    name: "Kodak Tri-X 400",
    source_url: "https://fujixweekly.com/2020/06/18/fujifilm-x100v-film-simulation-recipe-kodak-tri-x-400/",
    type: "single",
    recipe_name: "Kodak Tri-X 400",
    description: "Emulates Kodak Tri-X 400 — the definitive high-grain documentary B&W film. The extreme WB shift (R+9/B−9) manipulates tonal rendering so that the Acros simulation responds more like Tri-X's warm-tonality silver halide base. Clarity +4 and Shadow +3 together give bold shadow separation with crisp micro-contrast. ISO is intentionally high to generate grain as the creative element, not something to suppress.",
    usage: "Street, documentary, journalism, gritty urban. Shoot at ISO 1600–6400. Let the grain breathe — this is not a clean B&W recipe.",
    pros: [
      "Authentic Tri-X grain texture — looks genuinely like scanned film at ISO 3200",
      "Clarity +4 + Shadow +3 gives excellent tonal separation in flat or low-light scenes",
      "Acros simulation has the best B&W tonal rendering in the Fuji lineup",
      "The extreme WB shift is part of the published recipe; retain it when comparing tonal renderings",
    ],
    cons: [
      "Extreme R+9/B−9 WB shift looks wrong in color preview mode — disorienting until you commit to JPEG/film",
      "Grain Effect is active at low ISO too; higher ISO adds noise and changes the intended texture",
      "Grain can mask fine detail, but good focus and sound lens technique still matter",
      "Acros Standard filter chosen; other filters (Y/R/G) would change sky/skin tones — worth experimenting later",
    ],
    settings: [
      ["Film Sim",       "Acros (Standard — no filter)"],
      ["Dynamic Range",  "DR200"],
      ["Grain",          "Strong, Large"],
      ["CCE",            "Strong"],
      ["CCE Blue",       "Off"],
      ["White Balance",  "Daylight  R+9 / B−9"],
      ["Highlight",      "0"],
      ["Shadow",         "+3"],
      ["Sharpness",      "+1"],
      ["Clarity",        "+4"],
      ["ISO",            "1600–12800"],
      ["Exposure",       "+⅓ to +1"],
    ],
    filter_variants: [
      {
        filter: "Standard",
        active: true,
        summary: "Neutral, balanced tonality. No color adjustment applied.",
        best_for: "Any subject. A reliable baseline for indoor, outdoor, and mixed light.",
      },
      {
        filter: "+Y  Yellow",
        active: false,
        summary: "Slightly darkens blue sky, gentle contrast boost.",
        best_for: "Everyday urban and street photography. Natural-looking with a mild punch.",
      },
      {
        filter: "+R  Red",
        active: false,
        summary: "Dramatically darkens sky, water, and blue tones. Strong graphic contrast. Lightens warm/skin tones.",
        best_for: "Dramatic skies, architectural photography, bold clouds.",
      },
      {
        filter: "+G  Green",
        active: false,
        summary: "Lightens foliage and skin tones, slightly darkens sky and red tones.",
        best_for: "Outdoor portraits and nature photography with lots of greenery.",
      },
    ],
  },
];

// ─── My Custom Setup (camera-aware) ───
// "fuji-slots" cameras render MY_CUSTOM_SLOTS with the shared Fuji visual standard.
// "fuji-scenarios" cameras separate C-bank menu recommendations, physical controls,
// and FS recipe memories (X-E5). These do not reuse the X-T50 C1–C7 recipe slots.
// "om-dial" cameras render shooting modes + creative color/mono profiles via buildOmVisual().
// "empty" cameras show a placeholder until the user fills in real data.
const MY_CUSTOM_SETUPS = {
  "Fujifilm X-T50": { type: "fuji-slots" },
  "Fujifilm X-E5": {
    type: "fuji-scenarios",
    intro: "Planned X-E5 starter setup: C1–C7 recall scenario-related menu settings; FS1–FS3 carry three consistent looks. This is a programming guide, not confirmation that the settings are already saved on the camera. Keep the X-T50 slots and X-M5 placeholder separate.",
    control_note: "Unlike the OM-3’s mode dial, recalling a Fuji C bank does not move the physical shutter dial, aperture ring/dial, or S/C/M focus selector. Set those controls by hand as shown. The film-simulation dial’s C position is also not the same thing as the C1–C7 custom banks.",
    baseline: [
      ["Image quality", "FINE+RAW"], ["File format", "JPEG, not HEIF (HEIF disables Clarity)"],
      ["D Range Priority", "Off, so the recipe’s DR and tone settings remain available"],
      ["Auto update custom settings", "DISABLE for repeatable C-bank baselines"],
      ["FS RECIPE", "ON for FS1, FS2 and FS3"],
      ["Exposure compensation", "Start at 0, then judge the subject and highlights; not a fixed value for all scenarios"],
    ],
    autoIso: [
      { id: "AUTO1", name: "Everyday / People", base: 125, ceiling: 6400, min_shutter: "1/250" },
      { id: "AUTO2", name: "Kids / Action", base: 125, ceiling: 12800, min_shutter: "1/1000" },
      { id: "AUTO3", name: "Low Light", base: 125, ceiling: 12800, min_shutter: "1/125" },
    ],
    auto_iso_note: "The minimum-shutter preferences help in aperture-priority shooting, but are not hard floors once ISO reaches its ceiling. In M or S, the manually selected shutter takes priority. ISO 125 is the normal base; FS2’s DR400 requires at least ISO 500, and FS3’s DR200 requires at least ISO 250. Follow the camera’s allowed ISO rather than forcing 125.",
    instructions: [
      "Use the still-photo menus. Set FINE+RAW and JPEG first. Under IMAGE QUALITY SETTING → FILM SIMULATION DIAL SETTING, assign FS1 = Classic Chrome, FS2 = Classic Chrome, and FS3 = ACROS (standard/no filter). Set FS RECIPE to ON for each FS position; assigning a film simulation alone does not store a complete recipe.",
      "Rotate to FS1 and enter its image-quality settings below, then repeat for FS2 and FS3. Keep D Range Priority Off. The X-E5 manual describes separate image-quality registration with FS RECIPE enabled; confirm each position retains the intended WB, WB shift, DR, tone, grain, Color Chrome, sharpness, High ISO NR and Clarity before continuing.",
      "Configure AUTO1/AUTO2/AUTO3 as listed. These are shooting ISO profiles, not FS recipe memories. ISO ceilings and exposure compensation shown with the recipes below are field guidance, not settings automatically recalled by FS1–FS3.",
      "Return the film-simulation dial to FS1 after programming all three looks. Build C1’s menu baseline, then save it via IMAGE QUALITY SETTING → EDIT/SAVE CUSTOM SETTING → CREATE NEW C1 → OK. Name it using EDIT CUSTOM NAME. Copy this baseline to C2–C7 before changing the scenario-related menu settings in each bank’s EDIT/CHECK screen. Rename every copied bank (for example STREET, ACTION, PEOPLE, NIGHT PPL, STATIC, LANDSCAPE, MOTION). This helps keep the three FS assignments consistent across all banks.",
      "Set AUTO UPDATE CUSTOM SETTING to DISABLE. After editing a C bank, use SAVE THE CHANGES to commit it deliberately; red-dot changes are not automatically saved with auto update disabled. Recall banks through SELECT CUSTOM SETTING, or add that selection to your Q menu if desired.",
      "C banks also contain image-quality and FILM SIMULATION DIAL SETTING entries. Do not assume every C bank excludes the FS configuration: recall all seven banks and rotate through FS1–FS3, checking the expected recipe settings each time. Keep FS RECIPE enabled and synchronize any accidentally different assignments/settings before relying on the setup.",
      "For each recalled scenario, set the physical shutter dial, lens aperture control and focus selector manually. Use shutter dial A for aperture priority, or T plus the rear command dial for a chosen shutter. P forces Program AE on the X-E5. Always verify the actual exposure mode, shutter, aperture, ISO and AF indication on the display.",
    ],
    sources: [
      ["X-E5: FS dial and FS RECIPE", "https://fujifilm-dsc.com/en/manual/x-e5/about_this_camera/parts/#fs_dial"],
      ["X-E5: custom banks / image quality", "https://fujifilm-dsc.com/en/manual/x-e5/menu_shooting/image_quality_setting/"],
      ["X-E5: Auto ISO", "https://fujifilm-dsc.com/en/manual/x-e5/taking_photo/iso/"],
      ["X-E5: exposure controls", "https://fujifilm-dsc.com/en/manual/x-e5/taking_photo/shooting_mode/"],
      ["X-E5: focus selector", "https://fujifilm-dsc.com/en/manual/x-e5/taking_photo/autofocus/"],
    ],
    modes: [
      {
        slot: "C1", name: "Street / Everyday",
        purpose: ["Walkaround", "Travel", "Street", "Casual scenes"],
        settings: [["ISO", "AUTO1"], ["AF MODE", "Single Point; Zone if following movement"],
                   ["Face/Eye Detection", "Off for precise point placement; enable for people"],
                   ["Subject Detection", "Off"], ["Drive", "Single"], ["Shutter Type", "Mechanical"],
                   ["IS Mode", "Shooting Only or Continuous, as preferred"], ["Photometry", "Multi when detection is Off"]],
        manual_settings: [["Exposure mode", "M + Auto ISO"], ["Shutter dial", "T → 1/250; 1/500 for faster pedestrians"],
                          ["Aperture ring/dial", "f/4, or f/2.8–f/5.6 to suit the scene"], ["Focus selector", "S for still scenes; C for changing distance"]],
        why: ["1/250 is a useful starting point for normal walking movement.", "Keep the subject choice deliberate; switch the physical focus selector to C when distance changes."],
        shortcut: "C1 = everyday movement · FS1 color or FS3 documentary B&W",
      },
      {
        slot: "C2", name: "Kids / Action",
        purpose: ["Kids", "Pets", "Cyclists", "Quick gestures"],
        settings: [["ISO", "AUTO2"], ["AF MODE", "Zone"], ["AF-C Custom Settings", "Set 1 as the starting point"],
                   ["Face/Eye Detection", "On for people"], ["Subject Detection", "Off for people; select the matching animal category for pets"],
                   ["Drive", "CL: short low-speed bursts"], ["Shutter Type", "Mechanical initially"],
                   ["IS Mode", "Shooting Only or Continuous"], ["Photometry", "Multi baseline; detection can determine exposure behavior"]],
        manual_settings: [["Exposure mode", "M + Auto ISO"], ["Shutter dial", "T → 1/1000; 1/1600–1/2000 for faster action"],
                          ["Aperture ring/dial", "f/2.8–f/4, or widest useful opening"], ["Focus selector", "C (AF-C)"]],
        why: ["Freeze the movement before trying to minimize ISO noise; allow AUTO2’s 12800 ceiling when necessary.",
              "Use short bursts with updating AF. FS1 has Clarity 0 and is the simplest responsive default; test FS2/FS3 processing and burst behavior rather than silently changing their recipes."],
        shortcut: "C2 = unpredictable movement · FS1 first",
      },
      {
        slot: "C3", name: "People / Portraits",
        purpose: ["Friends and family", "Portraits", "Environmental portraits"],
        settings: [["ISO", "AUTO1"], ["AF MODE", "Single Point or Wide/Tracking as the subject requires"],
                   ["Face/Eye Detection", "On; Eye Auto, then confirm the intended eye"], ["Subject Detection", "Off"],
                   ["Drive", "Single or short CL burst"], ["Shutter Type", "Mechanical"], ["IS Mode", "Shooting Only"],
                   ["Photometry", "Multi baseline; face detection can take priority"]],
        manual_settings: [["Exposure mode", "A + Auto ISO"], ["Shutter dial", "A; watch for at least 1/250 with people"],
                          ["Aperture ring/dial", "f/1.4–f/2.8 if the lens permits; f/4–f/5.6 for groups"],
                          ["Focus selector", "S for a still pose; C for swaying/walking subjects"]],
        why: ["Make depth of field the main decision, then check the actual shutter speed.",
              "If A mode drops below a safe speed at the ISO ceiling, use T → 1/250 with a manual aperture for M + Auto ISO, or add light."],
        shortcut: "C3 = the face matters · FS1, or FS3 for a gritty portrait",
      },
      {
        slot: "C4", name: "Night / People",
        purpose: ["Evening streets", "Restaurants", "Available-light people"],
        settings: [["ISO", "AUTO3"], ["AF MODE", "Single Point; use Zone if following movement"],
                   ["Face/Eye Detection", "On if reliable; otherwise Off and choose a lit facial detail"], ["Subject Detection", "Off"],
                   ["Drive", "Single or short CL burst"], ["Shutter Type", "Mechanical; test artificial-light banding"],
                   ["IS Mode", "Shooting Only or Continuous"], ["Photometry", "Multi baseline; protect important highlights"]],
        manual_settings: [["Exposure mode", "M + Auto ISO"], ["Shutter dial", "T → 1/125; 1/250 if the person moves"],
                          ["Aperture ring/dial", "Wide open, typically f/1.4–f/2.8 where available"], ["Focus selector", "S for still people; C if distance changes"]],
        why: ["IBIS steadies the camera, not a person. Do not default to 1/15 just because stabilization is available.",
              "AUTO3 can reach ISO 12800. Adjust exposure using the face and highlight warnings, not a blanket negative compensation rule."],
        shortcut: "C4 = low light, living subjects · FS1 or FS3; avoid FS2 under mixed artificial light",
      },
      {
        slot: "C5", name: "Static / Low Light",
        purpose: ["Buildings at dusk", "Museums", "Interiors", "Still details"],
        settings: [["ISO", "AUTO3"], ["AF MODE", "Single Point"], ["Face/Eye Detection", "Off"],
                   ["Subject Detection", "Off"], ["Drive", "Single"], ["Shutter Type", "Mechanical"],
                   ["IS Mode", "Shooting Only or Continuous handheld"], ["Photometry", "Multi"]],
        manual_settings: [["Exposure mode", "M + Auto ISO"], ["Shutter dial", "T → 1/30 initially; test 1/15–1/60 with the lens and stance"],
                          ["Aperture ring/dial", "f/1.4–f/2.8 if available; use a tripod for more depth of field"],
                          ["Focus selector", "S; M with magnification if autofocus struggles"]],
        why: ["The slower shutter is for static subjects only; switch to C4’s speeds when people enter the frame.",
              "AUTO3’s 1/125 preference does not override a manually chosen 1/30 in M. Check for shake at full magnification; longer lenses may need more speed."],
        shortcut: "C5 = steady camera, still scene · FS1 or FS3",
      },
      {
        slot: "C6", name: "Landscape / Architecture",
        purpose: ["Daylight landscape", "Architecture", "Careful compositions"],
        settings: [["ISO", "AUTO1 for handheld versatility; fixed low ISO is a deliberate alternative"],
                   ["AF MODE", "Single Point"], ["Face/Eye Detection", "Off"], ["Subject Detection", "Off"],
                   ["Drive", "Single; use a 2 s self-timer deliberately on a tripod"], ["Shutter Type", "Mechanical"],
                   ["IS Mode", "On handheld; follow body/lens guidance on a stable tripod"], ["Photometry", "Multi"]],
        manual_settings: [["Exposure mode", "A + Auto ISO initially"], ["Shutter dial", "A; watch wind movement and handheld sharpness"],
                          ["Aperture ring/dial", "f/5.6–f/8, then choose focus distance for near-to-far detail"],
                          ["Focus selector", "S; M for a fixed/tripod composition if useful"]],
        why: ["AUTO1’s 1/250 preference is a useful handheld baseline, not a mandate to shoot at high ISO.",
              "FS2 suits sunny daylight, but DR400 needs ISO 500 or above. Avoid forcing ISO 125 with that look; stop down for depth of field, not automatically to f/16."],
        shortcut: "C6 = compose slowly · FS2 in sun, FS1 in mixed/softer light, FS3 for graphic B&W",
      },
      {
        slot: "C7", name: "Panning / Creative Motion",
        purpose: ["Cyclists passing", "Moving vehicles", "Intentional background streaks"],
        settings: [["ISO", "AUTO1 initially; choose the lowest permitted ISO manually in bright light"],
                   ["AF MODE", "Zone"], ["AF-C Custom Settings", "Set 1 initially"], ["Face/Eye Detection", "Off unless the target is a person"],
                   ["Subject Detection", "Off or a matching supported category"], ["Drive", "Short CL bursts"],
                   ["Shutter Type", "Mechanical initially"], ["IS Mode", "Test the result; try Off if stabilization fights the pan"],
                   ["Photometry", "Multi baseline"]],
        manual_settings: [["Exposure mode", "S initially"], ["Shutter dial", "T → 1/60; explore 1/30–1/125"],
                          ["Aperture ring/dial", "A (auto); use M if you need to choose both aperture and shutter"], ["Focus selector", "C (AF-C)"]],
        why: ["Follow the subject smoothly before, during and after the shot. A slower shutter is a creative choice, not a failed attempt to freeze motion.",
              "An ND filter may be needed in sun, especially with FS2’s ISO 500 minimum. A manually chosen S-mode shutter is not limited by AUTO1’s 1/250 preference."],
        shortcut: "C7 = motion is the point · FS1 or FS3; FS2 only when light and ND control allow it",
      },
    ],
    filmSlots: [
      {
        id: "FS1", recipe_name: "Reggie's Portra", role: "Everyday color / people / adaptable Auto WB",
        best_for: ["C1 Street", "C3 People", "C4 Night", "C5 Low Light"],
        image_quality_extras: [["High ISO NR", "-4"], ["D Range Priority", "Off"]],
        iso_guidance: "Recipe guidance: Auto ISO up to 6400. The selected C scenario controls ISO; C2/C4 may deliberately permit 12800 to preserve shutter speed.",
        exposure_guidance: "Judge each exposure individually; Reggie does not prescribe a fixed compensation.",
        notes: ["Keep Color Chrome FX Blue Weak for Reggie’s original recipe. Off is an optional X-Trans V matching tweak, not required; the source confirms Reggie himself keeps Weak.",
                "Auto WB and Clarity 0 make this the most flexible default. A diffusion filter is optional, not a camera setting or requirement."],
        extra_source_url: "https://fujixweekly.com/2025/12/03/reggies-portra-in-x-trans-v-cameras/",
      },
      {
        id: "FS2", recipe_name: "Kodak Gold 200", role: "Warm sunny daylight / travel / nostalgic color",
        best_for: ["C1 in sunshine", "C6 Landscape", "C3 environmental portraits in suitable daylight"],
        image_quality_extras: [["High ISO NR", "-4"], ["D Range Priority", "Off"]],
        iso_guidance: "DR400 needs at least ISO 500 on the X-E5. Recipe guidance caps Auto ISO at 6400; the C-bank ceiling is a separate shooting choice.",
        exposure_guidance: "Often +2/3 to +1 EV in suitable light, then inspect highlights; not a compulsory value for every frame.",
        notes: ["Daylight WB with R+4/B-5 is deliberately warm. Do not treat this as the default under tungsten, mixed artificial light, or neutral skin-color requirements.",
                "Clarity -2 may add a processing pause. Prefer FS1 for rapid response, or deliberately make a Clarity 0 variant and label it as a variation rather than the original recipe."],
      },
      {
        id: "FS3", recipe_name: "Kodak Tri-X 400", role: "Gritty monochrome / street / documentary",
        best_for: ["C1 Street", "C4 Night", "C5 Low Light", "C7 Motion"],
        image_quality_extras: [["High ISO NR", "-4"], ["D Range Priority", "Off"]],
        iso_guidance: "DR200 needs at least ISO 250, but the intended Tri-X character uses ISO 1600–12800. Choose 1600–3200 for cleaner modern texture, or 6400–12800 for rougher grain. FS3 does not raise ISO automatically.",
        exposure_guidance: "Typically +1/3 to +1 EV as a starting experiment; judge the subject and highlight tradeoff.",
        notes: ["Assign ACROS standard/no filter to FS3 to match the saved dataset; yellow/red/green filtration is a deliberate alternative that changes tonal separation.",
                "If you raise ISO manually for grain, return to the scenario’s normal ISO behavior when switching back to FS1/FS2. Clarity +4 can slow response; test before an action shoot."],
      },
    ],
  },
  "Olympus PEN-F": {
    type: "om-dial",
    modes: [
      {
        slot: "C1", name: "Street",
        purpose: ["General walkaround", "Street photography", "Discreet shooting", "Everyday scenes"],
        settings: [["Exposure mode","M + Auto ISO"], ["Shutter speed","1/250"], ["Aperture","f/4"],
                   ["Auto ISO ceiling","ISO 3200"], ["AF mode","S-AF"], ["AF area","Small / Single"],
                   ["Face/Eye Priority","Off"], ["Drive mode","Single"], ["Shutter","Silent"],
                   ["Stabilization","S-IS AUTO"], ["Metering","ESP"]],
        why: ["1/250 is fast enough for normal pedestrian movement.", "f/4 gives useful depth of field.",
              "Small AF lets you choose the subject instead of having face detection grab random people.",
              "Silent shutter makes this the default discreet walkaround mode."],
        shortcut: "C1 = normal life moving slowly",
      },
      {
        slot: "C2", name: "Action",
        purpose: ["Cyclists", "Kids", "Dogs", "Running people", "Events", "General movement"],
        settings: [["Exposure mode","M + Auto ISO"], ["Shutter speed","1/1000"], ["Aperture","f/2.8–f/4"],
                   ["Auto ISO ceiling","ISO 6400"], ["AF mode","C-AF"], ["AF area","Group"],
                   ["Face/Eye Priority","Off"], ["Drive mode","Sequential L"], ["Shutter","Mechanical"],
                   ["Stabilization","S-IS AUTO"], ["Metering","ESP"]],
        why: ["1/1000 freezes most casual action.", "C-AF tracks moving subjects.",
              "Sequential L is preferable to Sequential H when you want AF to continue updating between frames."],
        shortcut: "C2 = things moving quickly",
      },
      {
        slot: "C3", name: "People",
        purpose: ["Portraits", "Friends and family", "Environmental portraits", "People encountered while walking around"],
        settings: [["Exposure mode","A"], ["Aperture","f/1.8–f/2.8"], ["Auto ISO ceiling","ISO 3200"],
                   ["AF mode","S-AF"], ["AF area","All Targets"], ["Face/Eye Priority","On"],
                   ["Eye priority","Nearest eye"], ["Drive mode","Single"], ["Shutter","Mechanical"],
                   ["Stabilization","S-IS AUTO"], ["Metering","ESP"]],
        why: ["Aperture priority makes depth of field the primary decision.",
              "Face/Eye AF lets the camera handle focus placement.",
              "All Targets gives face detection the whole frame to work with."],
        shortcut: "C3 = the human face matters",
      },
      {
        slot: "C4", name: "Night / Low Light",
        purpose: ["Evening streets", "Cafés", "Restaurants", "Museums", "Interiors", "Night walkaround", "Low-light events"],
        settings: [["Exposure mode","M + Auto ISO"], ["Shutter speed","1/125"], ["Aperture","Wide open, typically f/1.8–f/2.8"],
                   ["Auto ISO ceiling","ISO 6400"], ["AF mode","S-AF"], ["AF area","Small / Single"],
                   ["Face/Eye Priority","On"], ["Drive mode","Single"], ["Shutter","Mechanical"],
                   ["Stabilization","S-IS AUTO"], ["Metering","ESP"]],
        why: ["For people: stay around 1/125–1/250.", "For static subjects: lower to 1/60, 1/30, or slower when stabilization allows.",
              "Let Auto ISO absorb most lighting changes."],
        shortcut: "C4 = the light has disappeared",
      },
    ],
    colorProfiles: [
      {
        id: "COLOR 1", name: "Soft Negative", role: "Portra-ish / warm negative / everyday color",
        best_for: ["People", "Travel", "Everyday photography", "Soft daylight", "Skin tones"],
        recipe_type: "COLOR",
        color_wheel: { yellow:-1, orange:1, orangeRed:1, red:0, magenta:-1, violet:-1, blue:-1, blueCyan:-1, cyan:-2, greenCyan:-2, green:-2, yellowGreen:-2 },
        shadows: -1, midtones: 2, highlights: -1, contrast: -1, sharpness: -1,
        white_balance: "Auto", wb_amber_offset: null, wb_green_offset: null,
        character: ["Warm colors remain alive.", "Greens and blues are restrained.", "Contrast is slightly softer.",
                    "Intended as a Portra-like role rather than an exact Portra reproduction."],
        good_combos: ["C3 People + COLOR 1", "C1 Street + COLOR 1 for warmer everyday scenes"],
        shortcut: "COLOR 1 = Soft",
      },
      {
        id: "COLOR 2", name: "Reportage", role: "Classic-Chrome-ish / documentary / muted street color",
        best_for: ["Street", "Architecture", "Trains", "Cafés", "Rainy weather", "Urban scenes", "Documentary photography"],
        recipe_type: "COLOR",
        color_wheel: { yellow:-2, orange:0, orangeRed:0, red:-2, magenta:-2, violet:-2, blue:-2, blueCyan:-2, cyan:-3, greenCyan:-3, green:-3, yellowGreen:-3 },
        shadows: 4, midtones: 0, highlights: -1, contrast: 1, sharpness: -1,
        white_balance: "Auto", wb_amber_offset: null, wb_green_offset: null,
        character: ["Most colors are desaturated.", "Reds and oranges retain more presence.",
                    "Stronger shadow character.", "Designed as a documentary / reportage look."],
        good_combos: ["C1 Street + COLOR 2", "C4 Night + COLOR 2"],
        shortcut: "COLOR 2 = Muted",
      },
      {
        id: "COLOR 3", name: "Punchy Slide", role: "Vivid slide-film style / colorful daylight",
        best_for: ["Summer", "Blue skies", "Flowers", "Seaside", "Colorful buildings", "Travel", "Strong sunlight", "Landscapes"],
        recipe_type: "COLOR",
        color_wheel: { yellow:1, orange:3, orangeRed:5, red:5, magenta:5, violet:5, blue:4, blueCyan:4, cyan:4, greenCyan:2, green:1, yellowGreen:0 },
        shadows: -4, midtones: 0, highlights: 4, contrast: 0, sharpness: -1,
        white_balance: "Auto", wb_amber_offset: null, wb_green_offset: null,
        character: ["Strong color separation.", "Punchy reds, blues and magentas.",
                    "Bright, energetic daylight rendering.", "Think slide film rather than negative film.",
                    "If it feels too intense: reduce the +5 values to roughly +3 before changing the rest of the recipe."],
        good_combos: ["C1 Street + COLOR 3 on sunny days", "C3 People + COLOR 3 for colorful environmental portraits"],
        shortcut: "COLOR 3 = Punch",
      },
    ],
    monoProfiles: [
      {
        id: "MONO 1", name: "Clean", role: "Neutral / clean / fine monochrome",
        best_for: ["Portraits", "Quiet scenes", "Architecture", "Timeless everyday photography", "Situations where grain would be distracting"],
        recipe_type: "MONO",
        monochrome_profile: "None", monochrome_color: null, monochrome_color_strength: 0,
        film_grain: "Off/Low", monochrome_vignetting: null,
        shadows: 0, midtones: 0, highlights: 0, contrast: 0, sharpness: 0,
        character: ["Clean tonal rendering.", "Minimal stylistic intervention.", "Useful as the neutral B&W baseline."],
        good_combos: ["C3 People + MONO 1", "C1 Street + MONO 1 for quieter B&W"],
        shortcut: "MONO 1 = Clean",
      },
      {
        id: "MONO 2", name: "Tri-X Street", role: "Classic B&W film / reportage / street",
        best_for: ["Street", "People", "Night", "Documentary work", "Gritty urban scenes"],
        recipe_type: "MONO",
        monochrome_profile: "Factory Mono 2", monochrome_color: "Yellow", monochrome_color_strength: 1,
        film_grain: "Medium", monochrome_vignetting: "Dark 1",
        shadows: 0, midtones: 0, highlights: 0, contrast: 0, sharpness: 0,
        character: ["Classic black-and-white film feel.", "Medium grain adds texture without overwhelming the image.",
                    "Yellow filtration gives gentle separation and remains usable with people.",
                    "Contrast and Highlight/Shadow kept at factory initially."],
        good_combos: ["C1 Street + MONO 2", "C4 Night + MONO 2", "C3 People + MONO 2 for grittier portraits"],
        shortcut: "MONO 2 = Film",
      },
      {
        id: "MONO 3", name: "Drama", role: "Dramatic / infrared-inspired / graphic B&W",
        best_for: ["Buildings", "Clouds", "Strong skies", "Hard sunlight", "Graphic compositions", "Deep shadows", "Architectural scenes"],
        recipe_type: "MONO",
        monochrome_profile: "Mono 3", monochrome_color: "Red", monochrome_color_strength: 2,
        film_grain: "Low", monochrome_vignetting: "Dark 1",
        shadows: 0, midtones: 0, highlights: 0, contrast: 1, sharpness: 0,
        character: ["Darker blue skies.", "Stronger cloud separation.", "More graphic contrast.",
                    "Designed to be deliberately dramatic rather than general purpose."],
        good_combos: ["C1 Street + MONO 3 for architecture", "C4 Night + MONO 3 for graphic night scenes"],
        shortcut: "MONO 3 = Drama",
      },
    ],
  },
  "OM System OM-3": {
    type: "om-dial",
    intro: "Suggested starter setup — not a record of settings already saved on the camera. Five photo C modes separate shooting situations; four COLOR and four MONO profiles separate visual styles. Start with Auto WB, A0/G0, Keep Warm Color Off, and RAW+JPEG. Test each combination before relying on it at an event.",
    instructions: [
      "Set the photo/movie dial to photo, then configure a mode in P/A/S/M. Save via MENU → photo tab → 1. Basic Settings/Image Quality → Custom Mode → C1–C5 → Assign → Set. Assign overwrites that slot.",
      "Name each slot under Custom Mode Name. Keep Save Settings at Reset for a repeatable baseline; Hold retains changes made while shooting in that C mode.",
      "For the looks below, select COLOR or MONO on the Creative dial and select the numbered profile. Reset that profile first (hold OK on the profile screen), then enter the listed adjustments. These are suggested custom looks, not factory preset values or exact film emulations.",
      "After saving, switch away and recall every C mode. Check exposure, AF, drive, WB and the selected Creative profile. Do not assume a C mode excludes picture/profile settings; verify the dial/profile combination on the camera.",
    ],
    source_url: "https://my.omsystem.com/consumer/manuals/cameras/OM-3_MANUAL_EN.pdf",
    source_label: "OM-3 manual — custom modes pp. 78–84; Creative profiles pp. 220–229",
    modes: [
      {
        slot: "C1", name: "Street / Everyday",
        purpose: ["Walkaround", "Street", "Travel", "People in their environment"],
        settings: [["Exposure mode","M + Auto ISO"], ["Shutter speed","1/250"], ["Aperture","f/4"],
                   ["Auto ISO ceiling","ISO 6400"], ["AF mode","S-AF"], ["AF target","Small"],
                   ["Subject Detection","Off"], ["Drive / shutter","Single / Mechanical"],
                   ["Stabilization","S-IS AUTO"], ["Metering","ESP"]],
        why: ["1/250 is a useful starting point for walking people; raise it for faster movement.",
              "Use mechanical shutter under artificial light to reduce electronic-shutter banding risk; switch to silent when discretion matters."],
        shortcut: "C1 = everyday movement · try COLOR 2",
      },
      {
        slot: "C2", name: "Action",
        purpose: ["Kids", "Dogs", "Cyclists", "Casual sports"],
        settings: [["Exposure mode","M + Auto ISO"], ["Shutter speed","1/1000"], ["Aperture","Widest useful aperture"],
                   ["Auto ISO ceiling","ISO 12800"], ["AF mode","C-AF"], ["AF target","Group"],
                   ["Subject Detection","Off; select Dogs & Cats for pets"], ["Drive / shutter","Sequential L / Mechanical"],
                   ["Stabilization","S-IS AUTO"], ["Metering","ESP"]],
        why: ["Start at 1/1000 for movement and raise it if motion still blurs.",
              "Continuous AF and a modest burst make timing easier. Only enable a detection category that matches the subject."],
        shortcut: "C2 = things moving quickly · try COLOR 3",
      },
      {
        slot: "C3", name: "People",
        purpose: ["Portraits", "Friends and family", "Environmental portraits"],
        settings: [["Exposure mode","A + Auto ISO"], ["Aperture","f/1.8–f/2.8, lens permitting"],
                   ["Auto ISO ceiling","ISO 6400"], ["AF mode","S-AF"], ["AF target","All"],
                   ["Subject Detection","Human"], ["Drive / shutter","Single / Mechanical"],
                   ["Stabilization","S-IS AUTO"], ["Metering","ESP"]],
        why: ["Use human/eye detection and confirm the intended eye is in focus.",
              "Watch the actual shutter speed: aim for at least 1/125–1/250 with people; switch to M + Auto ISO when you need a guaranteed floor."],
        shortcut: "C3 = the person matters · try COLOR 1 or MONO 1",
      },
      {
        slot: "C4", name: "Night / Low Light",
        purpose: ["Evening streets", "Cafés", "Interiors", "Available-light portraits"],
        settings: [["Exposure mode","M + Auto ISO"], ["Shutter speed","1/125 for people"],
                   ["Aperture","Wide open"], ["Auto ISO ceiling","ISO 12800"], ["AF mode","S-AF"],
                   ["AF target","Small"], ["Subject Detection","Off; Human for portraits"],
                   ["Drive / shutter","Single / Mechanical"], ["Stabilization","S-IS AUTO"], ["Metering","ESP"]],
        why: ["IBIS steadies the camera, not a moving person. Raise the shutter to 1/250 when needed.",
              "For static subjects, try 1/30 or slower with a steady stance. Protect bright signs using the histogram and exposure compensation."],
        shortcut: "C4 = light is scarce · try MONO 2",
      },
      {
        slot: "C5", name: "Landscape / CP Tools",
        purpose: ["Architecture", "Static landscapes", "Water", "Computational experiments"],
        settings: [["Exposure mode","A"], ["Aperture","f/4–f/5.6"], ["ISO","200 baseline"],
                   ["AF mode","S-AF"], ["AF target","Small"], ["Subject Detection","Off"],
                   ["Drive","Single; 2s self-timer on tripod"], ["Stabilization","S-IS AUTO handheld; Off on a stable tripod"],
                   ["CP features","Off at recall; enable the required tool deliberately"]],
        why: ["Keep the recalled mode ordinary so a computational setting does not surprise you on the next shot.",
              "Use High Res Shot for suitable static detail, Live ND for deliberate motion blur, or Live GND for a bright sky. Check each tool’s mode/lens restrictions in the manual."],
        shortcut: "C5 = compose slowly · try COLOR 3 or MONO 3",
      },
    ],
    colorProfiles: [
      {
        id: "COLOR 1", name: "Soft Everyday", role: "Suggested custom look · warm colors, restrained foliage",
        recipe_type: "COLOR",
        color_wheel: { yellow:-1, orange:1, orangeRed:1, red:0, magenta:-1, violet:-1, blue:-1, blueCyan:-1, cyan:-1, greenCyan:-2, green:-2, yellowGreen:-1 },
        shadows: -1, midtones: 1, highlights: -1, shading_effect: 0, contrast: -1, sharpness: -1,
        white_balance: "Auto", wb_amber_offset: 0, wb_green_offset: 0,
        best_for: ["People", "Soft daylight", "Travel"],
        character: ["Gentle tones without a fixed warm WB cast. Start here for skin-focused scenes."],
        good_combos: ["C3 People + COLOR 1", "C1 Street + COLOR 1"], shortcut: "COLOR 1 = Soft",
      },
      {
        id: "COLOR 2", name: "Muted Reportage", role: "Suggested custom look · quiet documentary color",
        recipe_type: "COLOR",
        color_wheel: { yellow:-2, orange:0, orangeRed:0, red:-1, magenta:-2, violet:-2, blue:-2, blueCyan:-2, cyan:-3, greenCyan:-3, green:-3, yellowGreen:-2 },
        shadows: -2, midtones: 0, highlights: 1, shading_effect: 0, contrast: 1, sharpness: -1,
        white_balance: "Auto", wb_amber_offset: 0, wb_green_offset: 0,
        best_for: ["Street", "Architecture", "Overcast urban scenes"],
        character: ["Subdued colors and darker shadows. On OM, shadows down / highlights up increases tonal separation."],
        good_combos: ["C1 Street + COLOR 2", "C4 Night + COLOR 2"], shortcut: "COLOR 2 = Muted",
      },
      {
        id: "COLOR 3", name: "Daylight Slide", role: "Suggested custom look · vivid, not an exact film match",
        recipe_type: "COLOR",
        color_wheel: { yellow:1, orange:2, orangeRed:3, red:3, magenta:2, violet:2, blue:3, blueCyan:2, cyan:2, greenCyan:1, green:1, yellowGreen:0 },
        shadows: -2, midtones: 0, highlights: 2, shading_effect: 0, contrast: 0, sharpness: -1,
        white_balance: "Auto", wb_amber_offset: 0, wb_green_offset: 0,
        best_for: ["Seaside", "Flowers", "Colorful buildings", "Landscapes"],
        character: ["A moderate saturation boost. Reduce boosted channels if reds or blues become too loud."],
        good_combos: ["C5 Landscape + COLOR 3", "C2 Action + COLOR 3 outdoors"], shortcut: "COLOR 3 = Vivid",
      },
      {
        id: "COLOR 4", name: "Neutral Reference", role: "Suggested custom look · reset then zero the adjustments",
        recipe_type: "COLOR",
        color_wheel: { yellow:0, orange:0, orangeRed:0, red:0, magenta:0, violet:0, blue:0, blueCyan:0, cyan:0, greenCyan:0, green:0, yellowGreen:0 },
        shadows: 0, midtones: 0, highlights: 0, shading_effect: 0, contrast: 0, sharpness: 0,
        white_balance: "Auto", wb_amber_offset: 0, wb_green_offset: 0,
        best_for: ["Comparing custom looks", "Scenes where restraint matters"],
        character: ["An unembellished comparison point. This replaces the softer factory COLOR 4 preset; it is not a description of that preset."],
        good_combos: ["Any C mode + COLOR 4 to compare against a styled look"], shortcut: "COLOR 4 = Reference",
      },
    ],
    monoProfiles: [
      {
        id: "MONO 1", name: "Clean", role: "Suggested custom look · start from reset MONO 1",
        recipe_type: "MONO", monochrome_profile: "MONO 1", monochrome_color: "None", monochrome_color_strength: 0,
        film_grain: "Off", shading_effect: 0, shadows: 0, midtones: 0, highlights: 0, contrast: 0, sharpness: 0,
        white_balance: "Auto", wb_amber_offset: 0, wb_green_offset: 0,
        best_for: ["Portraits", "Quiet scenes", "Architecture"], character: ["Clean monochrome without added grain or filtration."],
        good_combos: ["C3 People + MONO 1"], shortcut: "MONO 1 = Clean",
      },
      {
        id: "MONO 2", name: "Grainy Street", role: "Suggested custom look · reset MONO 2, then set the values below",
        recipe_type: "MONO", monochrome_profile: "MONO 2", monochrome_color: "Yellow", monochrome_color_strength: 1,
        film_grain: "Medium", shading_effect: 0, shadows: -1, midtones: 0, highlights: 1, contrast: 0, sharpness: -1,
        white_balance: "Auto", wb_amber_offset: 0, wb_green_offset: 0,
        best_for: ["Street", "Night", "Documentary scenes"], character: ["Visible texture and gentle yellow filtration; not an exact Tri-X emulation."],
        good_combos: ["C1 Street + MONO 2", "C4 Night + MONO 2"], shortcut: "MONO 2 = Texture",
      },
      {
        id: "MONO 3", name: "Graphic Sky", role: "Suggested custom look · reset MONO 3, then set the values below",
        recipe_type: "MONO", monochrome_profile: "MONO 3", monochrome_color: "Red", monochrome_color_strength: 2,
        film_grain: "Low", shading_effect: 0, shadows: -2, midtones: 0, highlights: 2, contrast: 1, sharpness: 0,
        white_balance: "Auto", wb_amber_offset: 0, wb_green_offset: 0,
        best_for: ["Clouds", "Buildings", "Hard sunlight"], character: ["Red filtration darkens blue skies. Watch highlights; this is deliberately contrasty."],
        good_combos: ["C5 Landscape + MONO 3"], shortcut: "MONO 3 = Drama",
      },
      {
        id: "MONO 4", name: "Soft Grey", role: "Suggested custom look · reset MONO 4, then set the values below",
        recipe_type: "MONO", monochrome_profile: "MONO 4", monochrome_color: "None", monochrome_color_strength: 0,
        film_grain: "Off", shading_effect: 0, shadows: 1, midtones: 1, highlights: -1, contrast: -1, sharpness: -1,
        white_balance: "Auto", wb_amber_offset: 0, wb_green_offset: 0,
        best_for: ["Overcast light", "Gentle portraits", "Quiet interiors"], character: ["Lifted shadows and restrained highlights; a softer alternative to MONO 2/3."],
        good_combos: ["C3 People + MONO 4", "C4 Night + MONO 4 for static scenes"], shortcut: "MONO 4 = Gentle",
      },
    ],
  },
  "Fujifilm X-M5": { type: "empty" },
};


// ─── SCENARIO CASES ──────────────────────────────────────────
// Real-world shooting situations with gear + recipe recommendations.
// Add new entries as you encounter noteworthy scenarios.
const MY_SCENARIOS = [
  {
    id: "wedding-dk-jul-2026",
    title: "Wedding in DK — July '26",
    date: "2026-07-18",
    tags: ["event", "outdoor", "indoor", "overcast"],
    background: "Small wedding (~30 guests) in Denmark. Church ceremony followed by villa garden reception. Weather: mostly overcast with occasional sun. Mixed lighting conditions — dim church interior, then soft diffuse outdoor light.",
    recommendations: [
      {
        slot: "C3",
        recipe: "Reggie's Portra",
        label: "Primary — all day",
        reason: "Auto WB adapts across church interior → overcast garden without any manual adjustment. Flattering skin tones (Classic Chrome, Shadow −1, Sharpness −2). DR Auto is fine in most situations; bump to DR200 if shooting backlit against bright windows.",
      },
      {
        slot: "C6",
        recipe: "Pacific Blues",
        label: "Garden reception — overcast",
        reason: "Overcast light is ideal for this recipe. Shadow +3 adds dark-tone depth while Clarity −3 softens local contrast; that combination can work well on candids and relaxed group shots. 5800K WB runs warm outdoors which is flattering in soft garden light. Switch back to C3 for portraits where skin accuracy matters.",
      },
      {
        slot: "C1",
        recipe: "X-T50 Film Dial — Universal Recipe",
        label: "Church — situational",
        reason: "Use selectively when the church offers interesting light (stained glass, candles, shafts of sun). Dial to PRO Neg. Std for soft flattering portraits or Classic Chrome for atmosphere. Avoid under flat tungsten — Auto WB White Priority can cast orange.",
      },
    ],
    settings_to_watch: [
      { dial: "Exposure compensation", note: "Most critical dial. Church interiors: start at +⅔. Overcast garden: +⅓. Don't let the camera guess." },
      { dial: "Auto ISO", note: "Confirm minimum shutter is fast enough for moving subjects (~1/125 for candids)." },
      { dial: "Film Sim (C1 only)", note: "PRO Neg. Std for skin-focused shots; Classic Chrome for atmospheric frames." },
      { dial: "DR override", note: "C3 uses DR Auto — switch to DR200 manually when shooting backlit subjects against bright windows." },
      { dial: "AF mode", note: "Face/Eye AF for portraits and group shots; Zone for candid documentary moments." },
    ],
    skip: ["C4 (Kodachrome 64 — strictly sunny direct sun)", "C5 (Kodak Gold 200 — extreme yellow WB shift needs direct sun)", "C7 (Tri-X — B&W only, narrow use at events)"],
  },
];

// ─── YOUR SAVED RECIPES (7 custom slots) ─────────────────────
// recipe_name: must EXACTLY match the name in the dataset (Grid tab).
// camera:      which of your bodies this is saved on.
// slot:        C1–C7 (the camera's custom setting slot).
// usage:       when/why you reach for this recipe (shown prominently).
// personal_notes: freeform observations (optional).
const MY_RECIPES = [];

// ─── RECIPE METADATA PATCHES ─────────────────────────────────
// Override computed badge labels for specific recipes without touching RECIPES.
// Keys must exactly match RECIPES[].name.
const RECIPE_META_PATCHES = {
  // "Recipe Name": { warmth_override: "warm", punch_override: "flat" }
  //
  // warmth_override: "warm" | "neutral" | "cool"
  // punch_override:  "punchy" | "balanced" | "flat"
};
